services:
  headscale:
    image: "headscale/headscale"
    container_name: "headscale"
    command: serve
    restart: unless-stopped
    volumes:
      - ./headscale/headscale/data:/var/lib/headscale
      - ./headscale/headscale/config:/etc/headscale

  headscale-master-api:
    build: ./headscale/api
    container_name: "headscale-master-api"
    restart: unless-stopped
    volumes:
      - ./headscale/headscale/data:/var/lib/headscale
      - ./headscale/headscale/config:/etc/headscale
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - HEADSCALE_CONTAINER_NAME=headscale

  headscale-master-web:
    build: ./headscale/web
    container_name: "headscale-master-web"
    restart: unless-stopped
    volumes:
      - ./headscale/headscale/data:/var/lib/headscale
      - ./headscale/headscale/config:/etc/headscale
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - API_BASE_URL=http://127.0.0.1:5000